site_name: 杨小哥博客

theme:
  name: material  # 安装pip install mkdocs mkdocs-material
  language: 'zh'
  logo: logo.jpg
  favicon: favicon.ico
  custom_dir: overrides

extra:
  search:  # 支持中文搜索
    language: 'jp'


# site_favicon: favicon.ico
site_author: 杨小哥
repo_name: github.com/yiouejv/blog
repo_url: https://github.com/yiouejv/blog
site_description: 杨小哥博客,yiouejv,python,python学习,mysql,数据库,游戏开发,skynet,数据结构,数据结构与算法,算法,lua,linux


nav:
  # - Coding Interview University:
  #   - readme: Coding Interview University/readme.md
  #   - 必备知识: Coding Interview University/必备知识.md

  # - 算法导论(第三版):
  #   - 插入排序: 算法导论/插入排序.md

  # - 算法:

  #   - 数据结构.严蔚敏_吴伟民:
  #     - 1. linux 编程环境搭建: 算法/c_data_struct/linux_编程环境搭建.md
  #     - 2. 绪论: 算法/c_data_struct/绪论.md

    # - leetcode:
    #   - 数组:
    #     - 6.Z字形变换: leetcode/数组/6.Z字形变换.md 
    #     - 11. 盛最多水的容器: leetcode/数组/11. 盛最多水的容器.md 
    #     - 26.删除排序数组中的重复项: leetcode/数组/26.删除排序数组中的重复项.md 
    #     - 27.移除元素: leetcode/数组/27.移除元素.md
    #     - 35. 搜索插入位置: leetcode/数组/35. 搜索插入位置.md
    #   - 链表:
    #     - 19. 删除链表的倒数第N个节点: leetcode/链表/19. 删除链表的倒数第N个节点.md 
    #     - 21. 合并两个有序链表: leetcode/链表/21. 合并两个有序链表.md 
    #     - 23. 合并K个排序链表(可以优化): leetcode/链表/23. 合并K个排序链表(可以优化).md 
    #     - 24. 两两交换链表中的节点: leetcode/链表/24. 两两交换链表中的节点.md 
    #     - 206. 反转链表: leetcode/链表/206. 反转链表.md 
    # - 滑动窗口原理: 算法/滑动窗口原理.md
    # - 排序算法: 
    #   - 1. 排序算法时间复杂度: 算法/排序算法时间复杂度.md
    #   - 2. 基本排序算法: 算法/排序算法.md
    #   - 3. 分治法和归并排序: 算法/分治法和归并排序.md
    #   - 4. 快速排序: 算法/快速排序.md
    # - 位运算: 算法/位运算.md
    # - 递归: 算法/递归.md
    # - 1. 复杂度分析-上: 算法/复杂度分析-上.md
    # - 2. 复杂度分析-下: 算法/复杂度分析-下.md
    # - 3. 数组: 算法/数组.md
    # - 4. 链表-上: 算法/链表-上.md
    # - 5. 链表-下: 算法/链表-下.md
    # - 6. 栈: 算法/栈.md
  - leetcode:
    - 14. 最长公共前缀: leetcode/14. 最长公共前缀.md

  - 数据结构和算法:
    - 数据结构和算法思维导图: 算法/数据结构和算法思维导图.md
    - 二分查找: 数据结构和算法/二分查找.md
    - 排序: 
      - 选择排序: 数据结构和算法/选择排序.md
      - 快速排序: 数据结构和算法/快速排序.md
      - 归并排序: 数据结构和算法/归并排序.md
    - 数组: 数据结构和算法/数组.md
    - 链表: 数据结构和算法/链表.md
    - 栈: 数据结构和算法/栈.md
    - 队列: 数据结构和算法/队列.md
    - 哈希表: 数据结构和算法/哈希表.md
    - 图和广度优先搜索: 数据结构和算法/图和广度优先搜索.md
    - 狄克斯特拉算法: 数据结构和算法/狄克斯特拉.md

  - lua:
    - lua 表的构造: lua/表的构造.md
    - lua select 函数: lua/select函数.md
    - lua 面向对象: lua/opp.md
    - lua pairs和ipairs: lua/pairs和ipairs.md
    - lua 错误处理 pcall & xpcall: lua/错误处理 pcall & xpcall.md
    - lua 协程实现生产者消费者: lua/协程实现生产者消费者.md
    - lua 单链表: lua/lua 实现单链表.md
    - lua 打印表: lua/lua 打印表.md
    - lua 解析json数据: lua/解析json数据.md
    - lua 工作中要注意的点: lua/工作中要注意的点.md
  - skynet:
    - 1. 并发编程和并行编程: skynet/并发编程和并行编程.md
    - 2. skynet 基于 Actor 模式的开源框架: skynet/skynet 基于 Actor 模式的开源框架.md
  - python:
    - python 语法: 
      - 1. python相关介绍: python/python相关介绍.md
      - 2. python基础语法: python/python基础语法.md
      - 3. 字符串: python/python字符串.md
      - 4. 循环: python/python循环.md
      - 5. 列表: python/python列表.md
      - 6. 元组: python/python元组.md
      - 7. 字典: python/python字典.md
      - 8. 集合: python/python集合.md
      - 9. 函数: python/python函数.md
      - 10. 作用域: python/python作用域.md
      - 11. 高阶函数: python/python高阶函数.md
      - 12. 递归: python/python递归.md
      - 13. 装饰器: python/python装饰器.md
      - 14. 模块: python/python模块.md
      - 15. 包: python/python包.md
      - 16. 异常: python/python异常.md
      - 17. 迭代器和生成器: python/python迭代器和生成器.md
      - 18. 字节串和字节数组: python/字节串和字节数组.md
      - 19. 文件读写: python/文件读写.md
      - 20. 字符编码: python/字符编码.md
      - 21. 面向对象编程: 
          - 基本语法: python/面向对象编程.md
          - 继承派生: python/继承派生.md
          - 运算符重载: python/python运算符重载.md
      - 22. 迭代器（高级）: python/迭代器（高级）.md
      - 补充知识点: python/补充知识点.md
    - python 库: 
       - os.path: python/常见路径操作.md
       - datetime: python/日期和时间.md
    - python 相关: 
      - 虚拟环境: python/虚拟环境.md
      - 调取阿里云短信api发送短信: python/调取阿里云短信api发送短信.md
      - DFA敏感词过滤算法的python实现: python/DFA敏感词过滤算法的python实现.md
      - pandas.DataFrame对行和列求和、添加新行和列，apply函数的使用: python/pandas.DataFrame对行和列求和、添加新行和列，apply函数的使用.md
      - 完全卸载Python for ubuntu: python/完全卸载Python for ubuntu.md
      - python计算金额decimal常用操作: python/python计算金额decimal常用操作.md
      - python实现MD5加密: python/python实现MD5加密.md
      - 基于Pytest框架的自动化测试开发实践: python/基于Pytest框架的自动化测试开发实践.md
      
    - django: 
      - 1. django介绍及安装: django/1_django介绍及安装.md
      - 2. django中的路由: django/2_django中的路由.md
      - 3. HttpRequest对象: django/3_django中的HttpRequest对象.md
      - 4. session和cookie: django/4_django中的session和cookie.md
      - 5. django中的模板: django/5_django中的模板.md
      - 6. django中的模型: django/6_django中的模型.md
      - 7. 模型中的关系映射: django/7_django模型中的关系映射.md
      - 8. 自带的后台管理: django/8_django自带的后台管理.md
      - 9. django视图之CBV的基本使用: drf/1.django视图之CBV的基本使用.md
      - 10. CBV中解决csrf认证的问题: drf/2.CBV中解决csrf认证的问题.md
      - 11. REST framework APIView 总结: drf/REST_framework_APIView_总结.md
      - 几个django 2.2和mysql使用的坑: drf/几个django 2.2和mysql使用的坑.md
      - Django2 DEBUG=False后静态文件无法加载: django/Django2 DEBUG=False后静态文件无法加载.md
      - Django之密码的加密和解密: django/Django之密码的加密和解密.md
      - 自定义过滤器和自定义标签: django/自定义过滤器和自定义标签.md
      - 扩展自定义manage命令: python/Django扩展自定义manage命令.md
  - php:
    - 安装pdo_mysql 扩展: php/安装pdo_mysql扩展.md
    - 部署php及安装相关插件: php/部署php项目及安装php相关插件.md
  - mysql:
      - 1. 数据库概述: 数据库/mysql/数据库概述.md
      - 2. 数据类型: 数据库/mysql/数据类型.md
      - 3. 表操作: 数据库/mysql/表操作.md
      - 4. 查询: 数据库/mysql/查询.md
      - 5. 约束索引: 数据库/mysql/约束索引.md
      - 6. 数据备份与恢复: 数据库/mysql/数据备份与恢复.md
      - 7. 调优和事务: 数据库/mysql/调优和事务.md
      - 8. python3数据库编程: 数据库/mysql/python3数据库编程.md
      - 9. 补充知识: 数据库/mysql/补充知识.md
  - mongodb:
      - 1. 开启之前: 数据库/mongodb/开启之前.md
      - 2. 基本概念: 数据库/mongodb/基本概念.md
      - 3. 数据类型: 数据库/mongodb/数据类型.md
      - 4. shell文档: 数据库/mongodb/shell文档.md
      - 5. 索引聚合: 数据库/mongodb/索引聚合.md
      - 6. 补充知识: 数据库/mongodb/补充知识.md
      - 7. python操作mongodb: 数据库/mongodb/python操作mongodb.md
  - 前端相关:
      - input checked 全选: 前端相关/input_checked_全选.md
      - 实现图片懒加载: 前端相关/使用scrollreveal实现图片懒加载.md
  - 工具:
    - linux 操作系统: tools/linux操作系统.md
    - subl 使用备注: tools/subl使用备注.md
    - shell 语言编程: tools/shell 语言编程.md
    - git:
      - 使用git: tools/git/use_git.md
      - unpack-objects failed: tools/git/unpack-objects.md
    # - docker:
      # - 容器时代的引领者: docker/容器时代的引领者.md
      # - Docker 的前世今生: docker/Docker 的前世今生.md
      # - Docker 的基本使用: docker/Docker 的基本使用.md
      # - Docker 版本及内核兼容性选择: docker/Docker 版本及内核兼容性选择.md
      # - 容器生命周期管理（上）: docker/容器生命周期管理（上）.md
      # - 容器生命周期管理（下）: docker/容器生命周期管理（下）.md
      # - 容器资源管理: docker/容器资源管理.md
      # - 深入剖析容器: docker/深入剖析容器.md
  - 理财:
    - 基金理财: 理财/基金理财.md
    - 股票理财: 理财/股票理财.md
    - 白手起家的百万富翁的秘密: 理财/白手起家的百万富翁的秘密.md
    - 自选股: 理财/自选股.md
  
  - 其他:
    - 怎么搭建一个VPN: 其他/怎么搭建一个VPN.md
    - 浮点数的二进制表示(IEEE 754标准): Coding Interview University/浮点数的二进制表示(IEEE 754标准).md
    - 分布式 ID 的 9 种生成方式: 其他/分布式 ID 的 9 种生成方式.md


  - 待学:
    - 待学记录: wait.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde